### ISSUE TITLE
Text for 2x2 number and secondary stat widget

### ISSUE THREAD

**Issue by t-pfaff** [patleeman/geckopush#2]
The docs say:
>For a 2 x 2 widget you can show a label next to the primary value. For a 1 x 1 if you exclude a number from the second item you can specify a text label instead.

However, I get the following error when I push to a 2x2 number and secondary stat widget:
`GeckoboardException: Widget accepts text or a secondary value only.`
Shouldn't the text be accepted?

**Comment by patleeman** [comment]
Hi!

Can you post a snippet of your code?

**Comment by patleeman** [comment]
This widget is slightly different than the others in that you need to add both the primary and secondary stats with the same .add_data() method call:

Here's an example:
```python
d = geckopush.Dashboard("API-KEY-GOES-HERE")
widget_key = "widget-key-goes-here"
ns = geckopush.NumberAndSecondaryStat(dashboard=d, widget_key=widget_key)
ns.add_data(primary_value=15, secondary_value=25)
ret = ns.push()
```

So if you want to add two numbers:

    ns.add_data(primary_value=15, secondary_value=25)

If you want to add a number and text:

    ns.add_data(primary_value=15, text="text goes here")
 
Finally, if you want to add a number and a line chart:

    ns.add_data(primary_value=15, secondary_value=[12345, 12345, 15555, 12345, 12322])


Is this the issue you were running into?

**Comment by t-pfaff** [comment]
Not quite the issue I meant. Sorry for not posting code earlier.

This doesn't work:
`ns.add_data(primary_value=value_current, secondary_value=value_last, text='test')`

Throwing the error: `GeckoboardException: Widget accepts text or a secondary value only.`

While the Geckoboard [docs](https://developer.geckoboard.com/#parameters-22) say (for `text`_optional_):
>For a 2 x 2 widget you can show a label next to the primary value. For a 1 x 1 if you exclude a number from the second item you can specify a text label instead.

So the above error shouldn't be thrown if it's a 2x2 widget, right?

**Comment by patleeman** [comment]
Oh wow, I didn't consider that use case.  I'll patch it and upload a fix.

**Comment by patleeman** [comment]
Okay, fix pushed.  Let me know if that works for you.

**Comment by t-pfaff** [comment]
Works!
