### ISSUE TITLE
Datasets API Support

### ISSUE THREAD

**Issue by patleeman** [patleeman/geckopush#3]
There has been a request for support for the new [Datasets API](https://developer-beta.geckoboard.com/api-reference/curl/).  

The new API allows developers to create and delete a schema and push data to it so a user can  build visualizations using a data set instead of pushing data directly to a specific widget.

This issue will be documenting support for this new feature.
## Links:

[Developer docs](https://developer-beta.geckoboard.com/api-reference/curl/)
[Forum discussion](https://community.geckoboard.com/t/beta-launch-of-our-new-custom-data-platform/202/11)

**Comment by patleeman** [comment]
Currently there are only three endpoints for this new functionality.

Each dataset has an `:id` which is simply a string to help identify the dataset on the geckoboard interface. 

Create dataset:
PUT https://api.geckoboard.com/datasets/:id

Replace all data in dataset:
PUT https://api.geckoboard.com/datasets/:id/data

Delete dataset:
DELETE https://api.geckoboard.com/datasets/:id


- It looks like you can only delete datasets via the API.
- Limits
  - 100 Datasets per account
  - 10 fields per dataset
  - 400 records per dataset

**Comment by patleeman** [comment]
# Potential Geckopush Datasets Workflow.
### How users can potentially interact with the new Datasets API.

1) User creates a dashboard object with API key.

```
from Geckopush import geckopush

api_key = '<api key from geckoboard>'
d = geckopush.Dashboard(api_key)
```

2) User creates a Dataset object
```
dataset_1 = geckopush.Dataset(dashboard=d, name="dataset_1")
```

3) User creates the schema
```
dataset_1.add_field(type="<type>", name="dataset_1_<type>")
```

?: Multi add fields?  Is there a better way for a user to create a schema? 

4) User adds the data
```
dataset_1.add_data(**kwargs)
```

?: Is this the best way? Add data items one at a time?  As a list of dictionaries?  as a list of lists/tuples with field names passed in a separate list?

5) User pushes data
```
dataset_1.push()
```
or
```
d.push_all()
```

**Comment by emiller3061** [comment]
The approach laid out above makes sense; it should provide users the functionality needed to create the dataset, but they would also need a way to delete it.  Right now I believe the only way to update data is to remove and replace the existing Dataset.  Although that is the case now, it appears they are planning to allow incremental updates moving forward based on [this post](https://community.geckoboard.com/t/beta-launch-of-our-new-custom-data-platform/202/3) in the Geckoboard Developer Community. 

Please be aware they are headed down this path, but it may be a while until that functionality is supported.

**Comment by patleeman** [comment]
I could also include a .delete() method on the dataset_1 object which would allow a dev to delete the dataset.
```
dataset_1.delete()
```

There are a couple of corner cases that may come up but once I get a chance to log into my test geckoboard account I can play around with the new functionality.

**Comment by emiller3061** [comment]
Hi Patrick,

I hope all is well. I'm following up to see if there is an updated status on this as Geckoboard appears to be starting to push the API quite a bit.  No rush on my end, I was just curious.

Thanks!
Eric

**Comment by patleeman** [comment]
Hey Sorry Eric,

I tried getting around to this but I just don't have the time or need to work on this lib any more. I'm going to close this issue and maybe somebody can fork the library and take over.
